# Pandas

1. read HTML(read_html)
2. To HTML(to_html)

In [8]:
import pandas as pd

In [9]:
html1=pd.read_html("https://en.wikipedia.org/wiki/Mobile_country_code")

In [10]:
type(html1)

list

In [11]:
html1[0]

,MCC,MNC,Brand,Operator,Status,Bands (MHz),References and notes
0,1,1,TEST,Test network,Operational,any,NaN
1,1,1,TEST,Test network,Operational,any,NaN
2,999,99,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"
3,999,999,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"

In [12]:
html2=pd.read_html("https://en.wikipedia.org/wiki/Economy_of_the_United_States",match="Government debt")

In [13]:
html[1]

,Year,GDP (in Bil. US$PPP),GDP per capita (in US$ PPP),GDP (in Bil. US$nominal),GDP per capita (in US$ nominal),GDP growth (real),Inflation rate (in Percent),Unemployment (in Percent),Government debt (inÂ % of GDP)
0,1980,2857.3,12552.9,2857.3,12552.9,-0.3%,13.5%,7.2%,NaN
1,1981,3207.0,13948.7,3207.0,13948.7,2.5%,10.4%,7.6%,NaN
2,1982,3343.8,14405.0,3343.8,14405.0,-1.8%,6.2%,9.7%,NaN
3,1983,3634.0,15513.7,3634.0,15513.7,4.6%,3.2%,9.6%,NaN
4,1984,4037.7,17086.4,4037.7,17086.4,7.2%,4.4%,7.5%,NaN
5,1985,4339.0,18199.3,4339.0,18199.3,4.2%,3.5%,7.2%,NaN
6,1986,4579.6,19034.8,4579.6,19034.8,3.5%,1.9%,7.0%,NaN
7,1987,4855.3,20001.0,4855.3,20001.0,3.5%,3.6%,6.2%,NaN
8,1988,5236.4,21376.0,5236.4,21376.0,4.2%,4.1%,5.5%,NaN
9,1989,5641.6,22814.1,5641.6,22814.1,3.7%,4.8%,5.3%,NaN
10,1990,5963.1,23848.0,5963.1,23848.0,1.9%,5.4%,5.6%,NaN
11,1991,6158.1,24302.8,6158.1,24302.8,-0.1%,4.2%,6.9%,NaN
12,1992,6520.3,25392.9,6520.3,25392.9,3.5%,3.0%,7.5%,NaN
13,1993,6858.6,26364.2,6858.6,26364.2,2.8%,3.0%,6.9%,NaN
14,1994,7287.3,27674.0,7287.3,27674.0,4.0%,2.6%,6.1%,NaN
15,1995,7639.8,28671.5,7639.8,28671.5,2.7%,2.8%,5.6%,NaN
16,1996,8073.1,29947.0,8073.1,29947.0,3.8%,2.9%,5.4%,NaN
17,1997,8577.6,31440.1,8577.6,31440.1,4.4%,2.3%,4.9%,NaN
18,1998,9062.8,32833.7,9062.8,32833.7,4.5%,1.5%,4.5%,NaN
19,1999,9631.2,34496.2,9631.2,34496.2,4.8%,2.2%,4.2%,NaN
20,2000,10251.0,36312.8,10251.0,36312.8,4.1%,3.4%,4.0%,NaN
21,2001,10581.9,37101.5,10581.9,37101.5,1.0%,2.8%,4.7%,53.1%
22,2002,10929.1,37945.8,10929.1,37945.8,1.7%,1.6%,5.8%,55.5%
23,2003,11456.5,39405.4,11456.5,39405.4,2.8%,2.3%,6.0%,58.6%
24,2004,12217.2,41641.6,12217.2,41641.6,3.9%,2.7%,5.5%,66.2%
25,2005,13039.2,44034.3,13039.2,44034.3,3.5%,3.4%,5.1%,65.5%
26,2006,13815.6,46216.9,13815.6,46216.9,2.8%,3.2%,4.6%,64.2%
27,2007,14474.3,47943.4,14474.3,47943.4,2.0%,2.9%,4.6%,64.6%
28,2008,14769.9,48470.6,14769.9,48470.6,0.1%,3.8%,5.8%,73.5%
29,2009,14478.1,47102.4,14478.1,47102.4,-2.6%,-0.3%,9.3%,86.7%
30,2010,15049.0,48586.3,15049.0,48586.3,2.7%,1.6%,9.6%,95.2%
31,2011,15599.7,50008.1,15599.7,50008.1,1.6%,3.1%,8.9%,99.5%
32,2012,16254.0,51736.7,16254.0,51736.7,2.3%,2.1%,8.1%,103.1%
33,2013,16880.6,53363.9,16880.6,53363.9,2.1%,1.5%,7.4%,104.3%
34,2014,17608.1,55263.8,17608.1,55263.8,2.5%,1.6%,6.1%,104.2%
35,2015,18295.0,57006.9,18295.0,57006.9,2.9%,0.1%,5.2%,104.6%
36,2016,18804.9,58179.6,18804.9,58179.6,1.8%,1.3%,4.9%,106.5%
37,2017,19612.1,60292.9,19612.1,60292.9,2.5%,2.1%,4.4%,105.5%
38,2018,20656.5,63165.2,20656.5,63165.2,3.0%,2.4%,3.9%,106.8%
39,2019,21539.9,65561.3,21539.9,65561.3,2.6%,1.8%,3.7%,108%
40,2020,21354.1,64461.6,21354.1,64461.6,-2.2%,1.2%,8.1%,131.8%
41,2021,23681.1,71257.9,23681.1,71257.9,6.1%,4.7%,5.4%,124.5%
42,2022,26006.9,77979.8,26006.9,77979.8,2.5%,8.0%,3.6%,118.6%
43,2023,27720.7,82715.1,27720.7,82715.1,2.9%,4.1%,3.6%,118.7%
44,2024,29167.7,86601.2,29167.7,86601.2,2.8%,2.9%,4.1%,121%
45,2025,30337.1,89677.8,30337.1,89677.8,2.2%,1.9%,4.4%,124.1%
46,2026,31526.9,92785.8,31526.9,92785.8,2.0%,2.1%,4.3%,126.6%
47,2027,32786.7,96070.1,32786.7,96070.1,2.1%,2.1%,4.2%,128.4%
48,2028,34096.0,99467.8,34096.0,99467.8,2.1%,2.1%,4.0%,130.2%
49,2029,35457.9,102987.0,35457.9,102987.0,2.1%,2.1%,4.0%,131.7%

In [14]:
html=pd.read_html("https://en.wikipedia.org/wiki/Minnesota",match="Average daily maximum and minimum temperatures for selected cities in Minnesota")

In [15]:
html[0]

              Location July (Â°F) July (Â°C) January (Â°F) January (Â°C)
0          Minneapolis     83/64     28/18         23/7       â4/â13
1           Saint Paul     83/63     28/17         23/6       â5/â14
2            Rochester     82/63     28/17         23/3       â5/â16
3               Duluth     76/55     24/13         19/1       â7/â17
4            St. Cloud     81/58     27/14        18/â1       â7/â18
5              Mankato     86/62     30/16         23/3       â5/â16
6  International Falls     77/52     25/11        15/â6       â9/â21

In [16]:
type(html[0])

pandas.core.frame.DataFrame

In [17]:
html[0].to_html('demo.html')